import{S as p}from"./assets/vendor-CgTBfC_f.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=n(e);fetch(e.href,a)}})();const m=[{preview:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820__480.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820_1280.jpg",description:"Hokkaido Flower"},{preview:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677_1280.jpg",description:"Container Haulage Freight"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785_1280.jpg",description:"Aerial Beach View"},{preview:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619__340.jpg",original:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619_1280.jpg",description:"Flower Blooms"},{preview:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334__340.jpg",original:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334_1280.jpg",description:"Alpine Mountains"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571_1280.jpg",description:"Mountain Lake Sailing"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272_1280.jpg",description:"Alpine Spring Meadows"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255_1280.jpg",description:"Nature Landscape"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843_1280.jpg",description:"Lighthouse Coast Sea"}];document.querySelector("ul.gallery");const d=m.map(o=>{let i=document.createElement("li");return i.classList.add("gallery-item"),i.innerHTML=`
                <a class="gallery-link" href="${o.original}">
            <img
              class="gallery-image"
              src="${o.preview}"
              data-source="${o.original}"
              alt="${o.description}"
            />
          </a>`,i});document.querySelector("ul.gallery").prepend(...d);const g=new p(".gallery-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});g.on("show.simplelightbox");const c=document.createElement("li");c.innerHTML=`<form class="feedback-form" autocomplete="off">
    <label>
      Email
      <input type="email" name="email" autofocus />
    </label>
    <label>
      Message
      <textarea name="message" rows="8"></textarea>
    </label>
    <button type="submit">Submit</button>
  </form>
  `;document.querySelector("ul.gallery").insertAdjacentElement("afterend",c);const r={email:"",message:""};localStorage.getItem("feedback-form-state").email&&localStorage.getItem("feedback-form-state").message!==""&&(t.elements.email.value=localStorage.feedback-t-state.email.parse(),t.elements.message.value=localStorage.feedback-t-state.message.parse());const t=document.querySelector("form.feedback-form");t.addEventListener("input",o=>{localStorage.getItem("feedback-form-state");try{JSON.parse(localStorage.getItem("feedback-form-state")).email&&localStorage.getItem("feedback-form-state").message}catch{console.log("error with JSON.parse")}});t.addEventListener("submit",o=>{if(t.email===""&&t.message==="")return alert("Fill please all fields");r.email=t.elements.email.value.trim(),r.message=t.elements.message.value.trim(),console.log(r),localStorage.setItem("feedback-form-state",JSON.stringify(r)),t.elements.email.value="",t.elements.message.value="",document.querySelector(".feedback-form").reset,localStorage.clear()});
//# sourceMappingURL=index.js.map
